package io.avaje.inject.generator;

import java.io.IOException;
import java.nio.file.Files;

final class PomMainClassWriter {

  private static final String JAR_PLUGIN_BLOCK =
      "  <!-- generated by avaje inject -->\n"
          + "      <plugin>\n"
          + "        <groupId>org.apache.maven.plugins</groupId>\n"
          + "        <artifactId>maven-jar-plugin</artifactId>\n"
          + "        <configuration>\n"
          + "          <archive>\n"
          + "            <manifest>\n"
          + "              <mainClass>%s</mainClass>\n"
          + "            </manifest>\n"
          + "          </archive>\n"
          + "        </configuration>\n"
          + "      </plugin>\n"
          + "    ";

  static void writeMainClass(String qualifiedMainClass) throws IOException {
    // always write the metadata file for Gradle and other build tools
    var mainClassFile = APContext.getBuildResource("avaje-main-class.txt");
    Files.writeString(mainClassFile, qualifiedMainClass);

    var pomPath = APContext.getBuildResource("").getParent().resolve("pom.xml");
    if (!pomPath.toFile().exists()) {
      return;
    }

    var pomContent = Files.readString(pomPath);
    String updatedContent;
    if (pomContent.contains("maven-jar-plugin")) {
      updatedContent = updateExistingJarPlugin(pomContent, qualifiedMainClass);
    } else {
      updatedContent = insertNewJarPlugin(pomContent, qualifiedMainClass);
    }

    if (updatedContent != null && !updatedContent.equals(pomContent)) {
      Files.writeString(pomPath, updatedContent);
      APContext.logNote("Updated maven-jar-plugin mainClass to %s in pom.xml", qualifiedMainClass);
    }
  }

  private static String updateExistingJarPlugin(String pomContent, String mainClass) {
    int jarPluginIndex = pomContent.indexOf("maven-jar-plugin");
    int closingPlugin = pomContent.indexOf("</plugin>", jarPluginIndex);
    if (closingPlugin == -1) {
      return null;
    }

    String before = pomContent.substring(0, jarPluginIndex);
    String pluginBody = pomContent.substring(jarPluginIndex, closingPlugin);
    String after = pomContent.substring(closingPlugin);

    if (pomContent.contains("<mainClass>")) {
      return pomContent.replaceAll("<mainClass>.*?</mainClass>", "<mainClass>" + mainClass + "</mainClass>");
    }

    // insert mainClass at the deepest existing nesting point
    int manifestClose = pluginBody.indexOf("</manifest>");
    if (manifestClose != -1) {
      String entry = "              <mainClass>" + mainClass + "</mainClass>\n              ";
      return before + new StringBuilder(pluginBody).insert(manifestClose, entry) + after;
    }

    int archiveClose = pluginBody.indexOf("</archive>");
    if (archiveClose != -1) {
      String manifestBlock =
          "            <manifest>\n"
              + "              <mainClass>" + mainClass + "</mainClass>\n"
              + "            </manifest>\n"
              + "          ";
      return before + new StringBuilder(pluginBody).insert(archiveClose, manifestBlock) + after;
    }

    int configClose = pluginBody.indexOf("</configuration>");
    if (configClose != -1) {
      String archiveBlock =
          "          <archive>\n"
              + "            <manifest>\n"
              + "              <mainClass>" + mainClass + "</mainClass>\n"
              + "            </manifest>\n"
              + "          </archive>\n"
              + "        ";
      return before + new StringBuilder(pluginBody).insert(configClose, archiveBlock) + after;
    }

    String configBlock =
        "  <configuration>\n"
            + "          <archive>\n"
            + "            <manifest>\n"
            + "              <mainClass>"
            + mainClass
            + "</mainClass>\n"
            + "            </manifest>\n"
            + "          </archive>\n"
            + "        </configuration>\n"
            + "      ";
    return before + pluginBody + configBlock + after;
  }

  private static String insertNewJarPlugin(String pomContent, String mainClass) {
    String pluginBlock = String.format(JAR_PLUGIN_BLOCK, mainClass);
    int pluginsIndex = findBuildPluginsClose(pomContent);
    if (pluginsIndex != -1) {
      return new StringBuilder(pomContent).insert(pluginsIndex, pluginBlock).toString();
    }
    // no <plugins> section - try inserting inside <build>
    int buildCloseIndex = pomContent.indexOf("</build>");
    if (buildCloseIndex != -1) {
      String pluginsWrap = "<plugins>\n    " + pluginBlock + "</plugins>\n  ";
      return new StringBuilder(pomContent).insert(buildCloseIndex, pluginsWrap).toString();
    }
    // no <build> section - insert before </project>
    int projectCloseIndex = pomContent.indexOf("</project>");
    if (projectCloseIndex == -1) {
      return null;
    }
    String buildWrap = "<build>\n    <plugins>\n    " + pluginBlock + "</plugins>\n  </build>\n";
    return new StringBuilder(pomContent).insert(projectCloseIndex, buildWrap).toString();
  }
  private static int findBuildPluginsClose(String pomContent) {
    int mgmtStart = pomContent.indexOf("<pluginManagement>");
    int mgmtEnd = mgmtStart != -1 ? pomContent.indexOf("</pluginManagement>", mgmtStart) : -1;
    int searchFrom = 0;
    while (true) {
      int idx = pomContent.indexOf("</plugins>", searchFrom);
      if (idx == -1) {
        return -1;
      }
      if (mgmtStart != -1 && idx > mgmtStart && idx < mgmtEnd) {
        searchFrom = idx + "</plugins>".length();
        continue;
      }
      return idx;
    }
  }
}
