package io.avaje.inject.generator;

import java.io.IOException;
import java.nio.file.Files;

final class PomMainClassWriter {

  private static final String JAR_PLUGIN_BLOCK =
      "  <!-- generated by avaje inject -->\n"
          + "      <plugin>\n"
          + "        <groupId>org.apache.maven.plugins</groupId>\n"
          + "        <artifactId>maven-jar-plugin</artifactId>\n"
          + "        <configuration>\n"
          + "          <archive>\n"
          + "            <manifest>\n"
          + "              <mainClass>%s</mainClass>\n"
          + "            </manifest>\n"
          + "          </archive>\n"
          + "        </configuration>\n"
          + "      </plugin>\n"
          + "    ";

  static void writeMainClass(String qualifiedMainClass) throws IOException {
    // always write the metadata file for Gradle and other build tools
    var mainClassFile = APContext.getBuildResource("avaje-main-class.txt");
    Files.writeString(mainClassFile, qualifiedMainClass);

    var pomPath = APContext.getBuildResource("").getParent().resolve("pom.xml");
    if (!pomPath.toFile().exists()) {
      return;
    }

    var pomContent = Files.readString(pomPath);
    String updatedContent;
    String pluginName;
    if (pomContent.contains("maven-shade-plugin")) {
      pluginName = "maven-shade-plugin";
      updatedContent = updateExistingShadePlugin(pomContent, qualifiedMainClass);
    } else if (pomContent.contains("maven-assembly-plugin")) {
      pluginName = "maven-assembly-plugin";
      updatedContent =
          updateExistingArchivePlugin(pomContent, "maven-assembly-plugin", qualifiedMainClass);
    } else if (pomContent.contains("maven-jar-plugin")) {
      pluginName = "maven-jar-plugin";
      updatedContent =
          updateExistingArchivePlugin(pomContent, "maven-jar-plugin", qualifiedMainClass);
    } else {
      pluginName = "maven-jar-plugin";
      updatedContent = insertNewJarPlugin(pomContent, qualifiedMainClass);
    }

    if (updatedContent != null && !updatedContent.equals(pomContent)) {
      Files.writeString(pomPath, updatedContent);
      APContext.logNote("Updated %s mainClass to %s in pom.xml", pluginName, qualifiedMainClass);
    }
  }

  private static String updateExistingShadePlugin(String pomContent, String mainClass) {
    int shadeIndex = pomContent.indexOf("maven-shade-plugin");
    int closingPlugin = pomContent.indexOf("</plugin>", shadeIndex);
    if (closingPlugin == -1) {
      return null;
    }

    String pluginBody = pomContent.substring(shadeIndex, closingPlugin);

    if (pluginBody.contains("<mainClass>")) {
      String updatedBody =
          pluginBody.replaceFirst(
              "<mainClass>.*?</mainClass>", "<mainClass>" + mainClass + "</mainClass>");
      return pomContent.substring(0, shadeIndex) + updatedBody + pomContent.substring(closingPlugin);
    }

    int transformersClose = pluginBody.indexOf("</transformers>");
    if (transformersClose != -1) {
      String transformerBlock =
          "<transformer implementation=\"org.apache.maven.plugins.shade.resource.ManifestResourceTransformer\">\n"
              + "                <mainClass>" + mainClass + "</mainClass>\n"
              + "              </transformer>\n            ";
      return new StringBuilder(pomContent)
          .insert(shadeIndex + transformersClose, transformerBlock)
          .toString();
    }

    int configClose = pluginBody.indexOf("</configuration>");
    if (configClose != -1) {
      String transformersBlock =
          "<transformers>\n"
              + "              <transformer implementation=\"org.apache.maven.plugins.shade.resource.ManifestResourceTransformer\">\n"
              + "                <mainClass>" + mainClass + "</mainClass>\n"
              + "              </transformer>\n"
              + "            </transformers>\n          ";
      return new StringBuilder(pomContent)
          .insert(shadeIndex + configClose, transformersBlock)
          .toString();
    }

    // no <configuration> in the shade plugin at all
    String configBlock =
        "  <configuration>\n"
            + "          <transformers>\n"
            + "            <transformer implementation=\"org.apache.maven.plugins.shade.resource.ManifestResourceTransformer\">\n"
            + "              <mainClass>" + mainClass + "</mainClass>\n"
            + "            </transformer>\n"
            + "          </transformers>\n"
            + "        </configuration>\n"
            + "      ";
    return new StringBuilder(pomContent).insert(closingPlugin, configBlock).toString();
  }

  private static String updateExistingArchivePlugin(
      String pomContent, String artifactId, String mainClass) {
    int pluginIndex = pomContent.indexOf(artifactId);
    int closingPlugin = pomContent.indexOf("</plugin>", pluginIndex);
    if (closingPlugin == -1) {
      return null;
    }

    String pluginBody = pomContent.substring(pluginIndex, closingPlugin);

    if (pluginBody.contains("<mainClass>")) {
      String updatedBody =
          pluginBody.replaceFirst(
              "<mainClass>.*?</mainClass>", "<mainClass>" + mainClass + "</mainClass>");
      return pomContent.substring(0, pluginIndex) + updatedBody + pomContent.substring(closingPlugin);
    }

    // insert mainClass at the deepest existing nesting point
    var sb = new StringBuilder(pomContent);

    int manifestClose = pluginBody.indexOf("</manifest>");
    if (manifestClose != -1) {
      String entry = "              <mainClass>" + mainClass + "</mainClass>\n              ";
      return sb.insert(pluginIndex + manifestClose, entry).toString();
    }

    int archiveClose = pluginBody.indexOf("</archive>");
    if (archiveClose != -1) {
      String manifestBlock =
          "            <manifest>\n"
              + "              <mainClass>" + mainClass + "</mainClass>\n"
              + "            </manifest>\n"
              + "          ";
      return sb.insert(pluginIndex + archiveClose, manifestBlock).toString();
    }

    int configClose = pluginBody.indexOf("</configuration>");
    if (configClose != -1) {
      String archiveBlock =
          "          <archive>\n"
              + "            <manifest>\n"
              + "              <mainClass>" + mainClass + "</mainClass>\n"
              + "            </manifest>\n"
              + "          </archive>\n"
              + "        ";
      return sb.insert(pluginIndex + configClose, archiveBlock).toString();
    }

    String configBlock =
        "  <configuration>\n"
            + "          <archive>\n"
            + "            <manifest>\n"
            + "              <mainClass>" + mainClass + "</mainClass>\n"
            + "            </manifest>\n"
            + "          </archive>\n"
            + "        </configuration>\n"
            + "      ";
    return sb.insert(closingPlugin, configBlock).toString();
  }

  private static String insertNewJarPlugin(String pomContent, String mainClass) {
    String pluginBlock = String.format(JAR_PLUGIN_BLOCK, mainClass);
    int pluginsIndex = findBuildPluginsClose(pomContent);
    if (pluginsIndex != -1) {
      return new StringBuilder(pomContent).insert(pluginsIndex, pluginBlock).toString();
    }
    // no <plugins> section - try inserting inside <build>
    int buildCloseIndex = pomContent.indexOf("</build>");
    if (buildCloseIndex != -1) {
      String pluginsWrap = "<plugins>\n    " + pluginBlock + "</plugins>\n  ";
      return new StringBuilder(pomContent).insert(buildCloseIndex, pluginsWrap).toString();
    }
    // no <build> section - insert before </project>
    int projectCloseIndex = pomContent.indexOf("</project>");
    if (projectCloseIndex == -1) {
      return null;
    }
    String buildWrap = "<build>\n    <plugins>\n    " + pluginBlock + "</plugins>\n  </build>\n";
    return new StringBuilder(pomContent).insert(projectCloseIndex, buildWrap).toString();
  }

  private static int findBuildPluginsClose(String pomContent) {
    int mgmtStart = pomContent.indexOf("<pluginManagement>");
    int mgmtEnd = mgmtStart != -1 ? pomContent.indexOf("</pluginManagement>", mgmtStart) : -1;
    int searchFrom = 0;
    while (true) {
      int idx = pomContent.indexOf("</plugins>", searchFrom);
      if (idx == -1) {
        return -1;
      }
      if (mgmtStart != -1 && idx > mgmtStart && idx < mgmtEnd) {
        searchFrom = idx + "</plugins>".length();
        continue;
      }
      return idx;
    }
  }
}
